name: Koki build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Build and upload APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Cache Gradle Wrapper and Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties') }}
            ${{ runner.os }}-gradle-cache-

      - name: Put keystore in place on filesystem to allow for signing builds
        run: echo "${{ secrets.KEYSTORE_FILE }}" | openssl base64 -d -out /tmp/keystore

      - name: Set up local.properties
        run: |
          echo -e 'signing.storeFilePath=/tmp/keystore\nsigning.keyPassword=${{ secrets.KEYSTORE_PASSWORD }}\nsigning.storePassword=${{ secrets.KEYSTORE_PASSWORD }}\nsigning.keyAlias=tuilakhanh0' > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: | 
        ./gradlew --refresh-dependencies assembleRelease
        echo "APK_FILE=$(find app/build/outputs/apk/release -name '*universal*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_ARMV8=$(find app/build/outputs/apk/release -name '*arm64*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_ARMV7=$(find app/build/outputs/apk/release -name '*arm32*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_X86=$(find app/build/outputs/apk/release -name '*x86-*.apk')" >> $GITHUB_ENV
        echo "APK_FILE_X64=$(find app/build/outputs/apk/release -name '*x86_64*.apk')" >> $GITHUB_ENV

      - name: Upload apk (universal)
        uses: actions/upload-artifact@v3
        with:
          name: Koki-universal
          path: ${{ env.APK_FILE }}

      - name: Upload apk (arm64-v8a)
        uses: actions/upload-artifact@v3
        with:
          name: Koki-arm64-v8a
          path: ${{ env.APK_FILE_ARMV8 }}

      - name: Upload apk (armeabi-v7a)
        uses: actions/upload-artifact@v3
        with:
          name: Koki-armeabi-v7a
          path: ${{ env.APK_FILE_ARMV7 }}

      - name: Upload apk (x86)
        uses: actions/upload-artifact@v3
        with:
          name: Koki-x86
          path: ${{ env.APK_FILE_X86 }}

      - name: Upload apk (x86_64)
        uses: actions/upload-artifact@v3
        with:
          name: Koki-x86_64
          path: ${{ env.APK_FILE_X64 }}

